
# Mounts in this project.
[[mounts]]
source = "docs"
target = "content"

[[mounts]]
source = "products"
target = "content/products"

[[mounts]]
source = "static"
target = "static"

[[mounts]]
# To add it to the server watch list.
# TODO(bep) this really needs to live in the theme, see
# https://github.com/gohugoio/hugo/issues/7635
source = "tailwind.config.js"
target = "assets/css/tailwind.config.js"

# The main theme.
# Note that the theme itself contains the mount configuration.
[[imports]]
path = "github.com/bep/linodedocs"


# Linode's OpenAPI definition.
[[imports]]
path = "github.com/linode/linode-api-docs"

[[imports.mounts]]
source = "openapi.yaml"
target = "assets/api/openapi.yaml"


